# Generated by Django 5.2 on 2026-03-08 19:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'brand',
                'verbose_name_plural': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ColorFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'color family',
                'verbose_name_plural': 'color families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PigmentFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'pigment family',
                'verbose_name_plural': 'pigment families',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='pigments.brand')),
            ],
            options={
                'verbose_name': 'formula',
                'verbose_name_plural': 'formulas',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.IntegerField(blank=True, help_text='Year CE', null=True)),
                ('date_end', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manuscripts', to='pigments.country')),
            ],
            options={
                'verbose_name': 'manuscript',
                'verbose_name_plural': 'manuscripts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hex_color', models.CharField(blank=True, help_text='CSS hex e.g. #A3B2C1', max_length=7)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paints', to='pigments.brand')),
            ],
            options={
                'verbose_name': 'paint',
                'verbose_name_plural': 'paints',
                'ordering': ['brand', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormulaPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('parts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('formula', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='pigments.formula')),
                ('paint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula_parts', to='pigments.paint')),
            ],
            options={
                'verbose_name': 'formula part',
                'verbose_name_plural': 'formula parts',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('color_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pigments', to='pigments.colorfamily')),
                ('pigment_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pigments', to='pigments.pigmentfamily')),
            ],
            options={
                'verbose_name': 'pigment',
                'verbose_name_plural': 'pigments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='formula',
            name='pigment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulas', to='pigments.pigment'),
        ),
        migrations.CreateModel(
            name='PigmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('pigment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pigments.pigment')),
            ],
            options={
                'verbose_name': 'pigment image',
                'verbose_name_plural': 'pigment images',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PigmentManuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pigment_links', to='pigments.manuscript')),
                ('pigment', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='manuscript_links', to='pigments.pigment')),
            ],
            options={
                'verbose_name': 'pigment manuscript link',
                'verbose_name_plural': 'pigment manuscript links',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
