# Generated by Django 5.2 on 2026-03-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='abbreviation',
            field=models.CharField(blank=True, help_text='Short label used in compact formula notation (e.g. "W" for white)', max_length=10),
        ),
    ]
